version: '3.9'

services:
  #MongoDB
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27018:27017"
    logging:
      driver: none
    restart: always
    volumes:
      - mongo_db:/data/db 

  #Node cie10 rest api
  api:
    container_name: api-cie10
    build: .
    ports:
      - "4000:3000"
    environment:
      MONGODB_URI: mongodb://mongo_db/cie10
    depends_on:
      - mongo_db
    volumes:
      - .:/usr/src/app

volumes:
  mongo_db: {}